#!/bin/bash

set -x

# VS code installation
sudo apt update
sudo apt upgrade -y
sudo apt install code -y

# Install Docker
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh ./get-docker.sh

# Install latest version of Docker
curl -fsSL https://test.docker.com -o test-docker.sh
sudo sh test-docker.sh && sudo docker run hello-world
